name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
template: |
    ## What’s Changed

    $CHANGES

categories:
    - title: '🚀 Features'
      label: 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'fix'
          - 'bugfix'
          - 'bug'
